openapi: '3.0.0'
info:
  title: Configurations
  contact:
    name: tyntec API Support
    url: http://www.tyntec.com/support
    email: support@tyntec.com
  version: '2.11'
  x-repository: https://github.com/tyntec/api-collection/blob/master/conversations
  x-major-version: v2
  x-postman-collection: postman.zip
servers:
  - url: https://api.tyntec.com/conversations/v3
security:
  - ApiKeyAuth: [ ]
tags:
  - name: "Configurations"
    description: |
      The Configurations allows you setup certain parts of a channels settings.

      Such as callback settings, credentials (where appropriate)
paths:
  /configurations:
    get:
      tags:
        - "Configurations"
      summary: Get account configuration
      operationId: getAccountConfiguration
      description: Returns the configuration of the API account
      responses:
        200:
          description: Configuration of the account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountConfiguration'
  /callback:
    put:
      tags:
        - "Configurations"
      summary: Update the callback
      operationId: updateAccountCallback
      description: Update the callback settings of the account. **Note** The complete object must be provided
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Callback'
      responses:
        200:
          description: Configuration of the account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountConfiguration'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
      description: |
        The API key used for this operation. We check as well that the API key has the phone number
        (either on sending messages or interacting with other phone number based features) assigned.
  responses:
    Default:
      description: Default response in case of any other error. Please check the error object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
    BadRequest:
      description: The request does not match our expectations. Please check the Problems object for details
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/Problem'
          example:
            status: 400
            violations: [
              {
                field: validate.request.whatsapp.contentType,
                message: must not be empty
              }
            ]
            title: Constraint Violation
  schemas:
    AccountConfiguration:
      type: object
      description: Configuration of an API account
      properties:
        scopes:
          $ref: '#/components/schemas/Scopes'
        callback:
          $ref: '#/components/schemas/Callback'
    Scopes:
      type: string
      enum:
        - messages:read
        - messages:write
        - channels:read
        - channels:write
        - callbacks:read
        - callbacks:write
        - media:read
        - media:write
    Callback:
      type: object
      properties:
        callbackVersion:
          type: integer
          minimum: 2
          maximum: 3
        signature:
          $ref: '#/components/schemas/Signature'
        header:
          $ref: '#/components/schemas/Header'
        inboundMessageUrl:
          type: string
          maxLength: 2000
        messageStatusUrl:
          type: string
          maxLength: 2000
        messageStatusEventFilter:
          type: array
          items:
            $ref: "#/components/schemas/EventTypes"
          minLength: 0
          default: []
    EventTypes:
      type: string
      description: Determines which kind of event is emitted by the API
      enum:
        - MessageStatus::accepted
        - MessageStatus::channelFailed
        - MessageStatus::deleted
        - MessageStatus::delivered
        - MessageStatus::failed
        - MessageStatus::seen
        - MessageStatus::unknown
    Signature:
      type: object
      required:
        - secret
        - method
      properties:
        secret:
          type: string
          minLength: 8
          maxLength: 125
        method:
          type: string
          enum:
            - HS256
            - HS512
    Header:
      type: object
      required:
        - key
        - value
      properties:
        key:
          type: string
        value:
          type: string
          minLength: 8
          maxLength: 125
    Problem:
      type: object
      additionalProperties: true
      description: The problem object follows the RFC-7807 (https://tools.ietf.org/html/rfc7807)
      required:
        - type
        - title
        - status
        - detail
      properties:
        type:
          description: A URI reference [RFC3986] that identifies the problem type
          example: https://docs.tyntec.com/problems/DataNotParseable
          type: string
        title:
          type: string
          example: Data given was not parseable
          description: A short, human-readable summary of the problem type.
        status:
          description: The HTTP status code (RFC7231, Section 6) generated by the origin server for this occurrence of the problem.
          type: string
          example: 400
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: |
            Unexpected end-of-input: expected close marker for Object (start marker at [Source: UNKNOWN; line: -1, column: -1) at [Source: UNKNOWN; line: 1, column: 97]